name: Checkout repository and verify Java installation on GitHub actions runner

on: [push, workflow_dispatch]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest Git commit
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Run Gradle clean test
        run: ./gradlew clean test